### ISSUE TITLE
Not able to install on KernalSU

### ISSUE THREAD

**Issue by soulspark666** [Magisk-Modules-Alt-Repo/open_webview#30]
[module_install_log_2023-11-13T00_11_32.304997.txt](https://github.com/Magisk-Modules-Alt-Repo/open_webview/files/13400543/module_install_log_2023-11-13T00_11_32.304997.txt)

Please help as I am not able to install this module.

**Comment by soulspark666** [comment]
But according to the recent changelog, this was made compatible with KernelSU.
https://github.com/Magisk-Modules-Alt-Repo/open_webview#v231
https://github.com/Magisk-Modules-Alt-Repo/open_webview/releases/tag/v2.3.1

**Comment by amteza** [comment]
> @amteza Right. Tq. But can you mention this in readme ? Caz most don't toggle it in the first place.

I did in XDA, but maybe @F3FFO can add it as a requirement in the README. I will send a PR to update it.

**Comment by amteza** [comment]
> That's okay. Most genz & boomers actually stopped using XDA. All the FOSS android project forums are discussed right in their repositories, which makes the most sense btw.

Yep, the only reason I used XDA was because of a query from someone in there. In any case PR created.

**Comment by soulspark666** [comment]
@amteza I enabled su for shell but it still is not able to install the module. Attaching logs for reference:
[module_install_log_2023-11-20T08_25_18.046151.txt](https://github.com/Magisk-Modules-Alt-Repo/open_webview/files/13406238/module_install_log_2023-11-20T08_25_18.046151.txt)

**Comment by soulspark666** [comment]
@foxjaw does not happen with me, instead it does download the webview and install it as a user app.

**Comment by amteza** [comment]
> @amteza I enabled su for shell but it still is not able to install the module. Attaching logs for reference: [module_install_log_2023-11-20T08_25_18.046151.txt](https://github.com/Magisk-Modules-Alt-Repo/open_webview/files/13406238/module_install_log_2023-11-20T08_25_18.046151.txt)

The issue you are experiencing has nothing to do with KernelSU. I just checked the logs. Is like it is not downloading the required files `chmod: /data/adb/modules_update/open_webview/addon/Volume-Key-Selector/tools: No such file or directory`.

Are you putting together a proper .zip file executing `create-module.sh`? I will let the developer chime in.

**Comment by amteza** [comment]
Okay, can you try this one?
[open-webview.zip](https://github.com/Magisk-Modules-Alt-Repo/open_webview/files/13406974/open-webview.zip)

**Comment by soulspark666** [comment]
> Okay, can you try this one? [open-webview.zip](https://github.com/Magisk-Modules-Alt-Repo/open_webview/files/13406974/open-webview.zip)

Failed for me too attaching logs:
[KernelSU_install_log_2023-11-20-12-47-36.log](https://github.com/Magisk-Modules-Alt-Repo/open_webview/files/13407558/KernelSU_install_log_2023-11-20-12-47-36.log)

**Comment by soulspark666** [comment]
I think so have not tried along with ksu, but previously when I only had magisk then it was working for me.

**Comment by amteza** [comment]
Okay, give me some time today to do some testing. Are you trying Android 14? What device are you trying with?

**Comment by soulspark666** [comment]
![Untitled](https://github.com/Magisk-Modules-Alt-Repo/open_webview/assets/37495396/b38002b5-d780-41f4-80ce-7358f1131135)
![Untitle1d](https://github.com/Magisk-Modules-Alt-Repo/open_webview/assets/37495396/99838dc4-ecff-42da-a15b-0c75adb01c04)

**Comment by lss4** [comment]
> I'm using [ponces A14 GSI](https://github.com/ponces/treble_build_aosp/releases) on [Redmi Note 10](https://m.gsmarena.com/xiaomi_redmi_note_10-10247.php). Nothing modified other than a [kernel with kernelSU support](https://github.com/Sr-Han/kernel_xiaomi_mojito) Even tested @lss4's [mulch-webview-overlay](https://github.com/A4Alpha/mulch-webview-overlay/issues/3#issuecomment-1820086524) which doesn't seems to work either.

I've confirmed this is due to [an overlay](https://github.com/phhusson/treble_experimentations/issues/2591) included in GSIs which added support for Bromite back then, which appears to be taking precedence over other overlays.

So unless support for other WebViews gets added into that overlay, GSI users need to remove or replace it.

**Comment by phhusson** [comment]
> I've confirmed this is due to https://github.com/phhusson/treble_experimentations/issues/2591 included in GSIs which added out-of-box support for Bromite back then. It appears to be taking precedence over other overlays, preventing them from taking effect.

You've removed that APK and confirmed the issue? The overlay in this module has priority 9999, the priority in TrebleDroid's overlay is only 8998. This overlay should still take precedence over TrebleDroid's.

> Lmao. I thought phhusson's was the purest AOSP without any modifications other than phh treble settings. 
Well that's wrong, the treble settings app in itself is largely useless without a lot of framework changes to actually apply those changes

> Strange that he's doing these underneath implementations silently.
I welcome any patch/recommendation on how to handle OEM's /vendor/overlay setting their own webviews. (Ideally this list of webviews simply wouldn't exist, and we'd trust the user)

**Comment by lss4** [comment]
> You've removed that APK and confirmed the issue? The overlay in this module has priority 9999, the priority in TrebleDroid's overlay is only 8998. This overlay should still take precedence over TrebleDroid's.

Thanks for the advice. So the issue here is probably different from what's going on with my unofficial Mulch overlay builds, as mine (actually A4Alpha's) has a priority of 1 compared to your 8998.

**Comment by soulspark666** [comment]
>@lss4's [mulch-webview-overlay](https://github.com/A4Alpha/mulch-webview-overlay/issues/3#issuecomment-1820086524) 

Btw this worked for me previously since I was not able to install this module, and have not tried it with the current ROM that I am using. Also want to add that I had to use the manual way to make it work since both the magisk module and the trwp flashable did not work from the mulch-webview-overlay repo.

**Comment by soulspark666** [comment]
Also in my case, I am not able to see any other webview present that might be prioritized.
Checked via:
```bash
su -c cmd overlay list | grep webview
su -c cmd package list packages | grep webview
```

**Comment by lss4** [comment]
I think the requirement to have a presence of webview packages as system app was something required only in older Android versions (around 9) and no longer holds true in newer Android versions.

This was mostly about a flag called `availableByDefault` which had effect back then but doesn't appear to be the case anymore -- For newer Android versions, if a package signature has been provided for a WebView provider, it can be installed as a user app regardless of that flag.

As such, I don't think the module needs to actually download and install the WebView packages as they're pretty large compared to the overlay itself. If the user happens to be offline, or has bad network connectivity, it would complicate things. Users should first install the overlays, then install the actual WebView package using their favorite methods and set it active.

> > This overlay should still take precedence over TrebleDroid's.
> 
> @phhusson But it didn't. I've removed priomisc overlay through root and then saw mulch webview. And no, the module overlay had priority 1 btw.

If you're referring to my unofficial Mulch WebView overlay builds, then yes. That one indeed has a priority of 1. Maybe I'll consider increasing the priority high enough to see if it will override `highpriomisc` for GSI users.

Considering this module here (Open WebView) has a priority of 9999 its issue with KernelSU might be something different, as I previously replied.

> > @lss4's [mulch-webview-overlay](https://github.com/A4Alpha/mulch-webview-overlay/issues/3#issuecomment-1820086524)
> 
> Btw this worked for me previously since I was not able to install this module, and have not tried it with the current ROM that I am using. Also want to add that I had to use the manual way to make it work since both the magisk module and the trwp flashable did not work from the mulch-webview-overlay repo.

The official repo hasn't been updated, and by default it installs to `/vendor/overlay` which no longer works since most recent Android versions (13 QPR3) -- you need to install to `/product/overlay`.

FYI, TWRP flashable variants of my unofficial builds are untested and there's a good chance it won't work with non-vndklite GSI variants, or dynamic system partitions.

> Also in my case, I am not able to see any other webview present that might be prioritized. Checked via:
> 
> ```shell
> su -c cmd overlay list | grep webview
> su -c cmd package list packages | grep webview
> ```

For your first command, through `adb shell` and with the Mulch WebView overlay I'm currently using, same here -- the overlay package is not listed, but it is indeed working per `dumpsys webviewupdate` output.

Also, Mulch's package name doesn't contain `webview`. It's called `us.spotco.mulch_wv`.

**Comment by soulspark666** [comment]
> 
> > Also in my case, I am not able to see any other webview present that might be prioritized. Checked via:
> > ```shell
> > su -c cmd overlay list | grep webview
> > su -c cmd package list packages | grep webview
> > ```
> 
> For your first command, through `adb shell` and with the Mulch WebView overlay I'm currently using, same here -- the overlay package is not listed (even without `grep`), but it is indeed working per `dumpsys webviewupdate` output.
> 
> Also, Mulch's package name doesn't contain `webview`. It's called `us.spotco.mulch_wv`.

Just verified with the Experimental Release you posted that this is indeed true.

**Comment by alheir** [comment]
> A complete & satisfactory solution is @lss4's overlay implementation, which is very small by itself & doesn't need to be online. And we can install/update the webview as per our convenience, considering the fact that webviews need not to be system installed.

Yup! I got it working on PocoF1 under CrDroid v10.1 ROM (A14) with KSU v0.7.6
